export const skills = [
  "Bicycle Repair",
  "Gardening Help",
  "Language Tutoring",
  "Graphic Design",
  "Cooking/Baking",
  "Yoga/Fitness Training",
  "Home Organization",
  "Pet Care",
  "Computer Help",
  "Music Lessons",
  "Photography",
  "Car Maintenance",
  "Spanish Language",
  "Guitar Lessons",
  "Home Repair",
  "Web Development",
  "Knitting/Crochet",
  "Yoga Instruction",
  "Meditation Guidance",
  "Financial Planning",
  "DIY Crafts",
];
